### ISSUE TITLE
install swi packages

### ISSUE THREAD

**Issue by JiesiGuo** [d-qn/2016_08_02_rioOlympicsAthletes#1]
How can I install these three packages?
library(swiMap)
library(swiTheme)
library(swiRcharts)

Many thanks!

**Comment by d-qn** [comment]
Hi,

these 3 packages are really just for personal/internal use. They don't do much, are poorly tested/documented and may relies on experimental features... This is how you would install them in theory:

```
install.packages("devtools")
library("devtools")

install_github("d-qn/swiTheme")
install_github("d-qn/swiMap")
install_github("d-qn/swiRcharts")
```

But frankly, I wouldn't get frustrated over installing these packages. Because of time constraint and laziness, I needed something as quickly as possible and I didn't aim to reduce dependencies. For the interactive graphic: 
- swiTheme is only a ggplot2 theme, it can be replaced by any other ggplot2 theme. 
- swiMap is only used to deal with country translations because the script will output 9 different html pages in 9 different languages. Also a feature and a complication you probably don't need
- swiRcharts: Also a package with some very context specific functions that can be dropped (such as the path to an iframe resizer javascript lib, only useful if you embed the graphic in an iframe)

I hope this helps though. Cheers
